services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: machin_barber
    ports:
      - "3307:3306"