services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: machin_barber
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://app:80
    depends_on:
      - app
    restart: unless-stopped